-- 1. TagCategory 더미 데이터
INSERT INTO tag_category (name, state) VALUES
                                           ('AI', 'ACTIVE'),
                                           ('개발', 'ACTIVE'),
                                           ('디자인', 'ACTIVE'),
                                           ('서비스', 'ACTIVE');

-- 2. AI 카테고리 태그 (color: green, variant: none)
INSERT INTO tag (category, color, variant, name, state) VALUES
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'LLM', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'ChatGPT', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'StableDiffusion', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'Midjourney', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'GenerativeAI', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'TensorFlow', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'PyTorch', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'Keras', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'MachineLearning', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'DeepLearning', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'Python', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', '데이터분석', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'DataScience', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'NLP', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'R', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'MLOps', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', 'AI윤리', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', '컴퓨터비전', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = 'AI'), 'green', 'none', '자율주행', 'ACTIVE');

-- 3. 개발 카테고리 태그 (color: blue, variant: none)
INSERT INTO tag (category, color, variant, name, state) VALUES
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'React', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'VueJS', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Angular', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'NextJS', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'TypeScript', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'JavaScript', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'NodeJS', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Spring', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Django', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'GoLang', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Java', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Python', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Docker', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Kubernetes', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'AWS', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Azure', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'GCP', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Cloud', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'SQL', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'NoSQL', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'MySQL', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'MongoDB', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Redis', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Git', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Testing', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Security', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'Microservice', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '개발'), 'blue', 'none', 'MSA', 'ACTIVE');

-- 4. 디자인 카테고리 태그 (color: purple, variant: none)
INSERT INTO tag (category, color, variant, name, state) VALUES
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'Figma', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'Sketch', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'AdobeXD', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'Illustrator', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'Photoshop', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'UI/UX', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'ProductDesign', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '그래픽디자인', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '브랜딩', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'InteractionDesign', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '디자인시스템', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'DesignThinking', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '프로토타이핑', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '와이어프레임', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'GUI', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', 'HTML/CSS', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '반응형웹', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '접근성', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '모션그래픽', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '웹표준', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '디자인툴팁', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '포트폴리오', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '타이포그래피', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '색상론', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '디자인'), 'purple', 'none', '사용성테스트', 'ACTIVE');

-- 5. 서비스 카테고리 태그 (color: orange, variant: none)
INSERT INTO tag (category, color, variant, name, state) VALUES
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '프로덕트매니저', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'PM', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '서비스기획', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'MVP', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '비즈니스모델', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'Agile', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'Scrum', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'Jira', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '노션', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '팀워크', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '그로스해킹', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'SEO', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'A/B테스트', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '데이터기반의사결정', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'CRM', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '스타트업', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '창업', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', 'IT법률', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '특허', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '투자', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '채용/면접', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '개발문화', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '커리어', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '회고록', 'ACTIVE'),
                                                            ((SELECT id FROM tag_category WHERE name = '서비스'), 'orange', 'none', '외주/프리랜서', 'ACTIVE');